### ISSUE TITLE
No mitte ei tööta

### ISSUE THREAD

**Issue by KasparTrumm** [pr11t/perearst#1]
Olen 81 aastane ja otsin uut perearsti, teie tarkvara ei tööta!1!1!

Ei tegelt, homme saad bugreport ja teeme korda.

**Comment by pr11t** [comment]
Tervisetrendi leht on muutunud, get_rating_from_tervisetrend peaks tegema näiteks. 
`soup.find_all("span", "rating")[0].strong.text.split(" - ")[0]`

Seal on palju mida paremini teha, PR oodatud :)
